config/routes.rb
LoginApp::Application.routes.draw do

  resources :subscriptions

  get "authentication/index"
  get "authentication/create"
  get "authentication/destroy"
  resources :servers, controller: "products"
  namespace :admin do
    resources :custom_images
  end

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: 'users/confirmations' }
  devise_scope :user do
    match 'login', to: "users/sessions#new", via: [:get, :post], as: "login"
    get "logout", to: "devise/sessions#destroy", as: "logout"
    match '/add_mail' => 'users/registrations#add_mail', via: [:get, :post]
    get '/auth/failure' => "users/sessions#new"
    get 'return' => "users/sessions#new"
  end
  root 'welcome#landing'
  match '/auth/:provider/callback' => 'authentication#create', via: [:get, :post]
  get "/launch_server" => "products#new", as: :launch_server
  get "/transaction_completed" => "products#show"
  match "/transaction_payment" => "products#transaction_details", via: [:get, :post]
  get '/pricing' => "welcome#pricing"
  get '/faq' => "static_pages#tos"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#error"
end

app/models/product.rb
include ActionView::Helpers::NumberHelper

class Product < ActiveRecord::Base
  include AwsAction

  belongs_to :user

  has_many :subscriptions
  default_scope { order('status') }

  before_create :add_ssh_keys

  def paypal_url
    if custom_image_id
      val = "Custom Image #{custom_image_id}"
    else
      if web_name == "AWS"
        val = product_type
      elsif web_name == "DigitalOcean"
        val = SizeType.find_by_size_id(size_type).name
      end
    end
    values = {
      :business => AppConfig.business_email,
      :cmd => '_xclick-subscriptions',
      :upload => 1,
      :item_name => name + ' (' + val + ')',
      :a3 => number_with_precision(cost, precision: 0),
      :p3 => '1',
      :t3 => 'M',
      :no_note => '1',
      :src => '1',
      :sra => '1',
      :cancel_return => AppConfig.cancel_url,
      :custom => id
    }
    AppConfig.paypal_url + "cgi-bin/webscr?" + values.to_query
  end
  
  def add_ssh_keys
    key = SSHKey.generate
    self[:private_ssh_key] = key.private_key
    self[:public_ssh_key] = key.ssh_public_key
  end

  # set_attributes
  # To be called only when cost and other calculable attributes are to be set.
  def set_attributes
    self.web_name = AppConfig.cloud[:name]
    if self.custom_image_id
      ci = CustomImage.find_by_id!(custom_image_id)
      self.cost = ci.price
      self.region = ci.region
      self.image_id = ci.remote_image_id

      #Map product_type or size_type since that is being used across the app.
      if ci.hosting == "AWS"
        pt = ProductType.find_by_memory!(ci.ram)
        self.product_type = pt.name
        self.size_type = nil
      elsif ci.hosting == "DigitalOcean"
        st = SizeType.find_by_memory!(ci.ram)
        self.size_type = st.size_id
        self.product_type = nil
      end
    else
      if type == "AWS"
        self.cost = ProductType.find_by_name(params[:product][:product_type]).cost_per_month
      elsif type == "DigitalOcean"
        self.cost = SizeType.find_by_size_id(params[:product][:size_type]).cost_per_month
      end
    end

    self.status = 'pending'
  end
end

app/models/product_type.rb
include ActionView::Helpers::NumberHelper

class ProductType < ActiveRecord::Base
  
  def memory
    unless self[:memory].blank?
      self[:memory].to_s + " GiB"
    else
      "0 GiB"
     end
  end

  def cost
    unless self[:cost_per_month].blank?
      "$" + number_with_precision(self[:cost_per_month], precision: 2).to_s + " per Month"
    else
      "$ 0 per Month"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  respond_to :html
  skip_before_action :authenticate_user!, only: [:transaction_details]
  before_action :set_digital_ocean
  
  def index
    respond_with @products = current_user.products.where(web_name: AppConfig.cloud[:name]).order('launch_time DESC')
  end

  def show
    if params[:cm]
      params_id = params[:cm]
      flash[:notice] = "Your Transaction is Completed. Thank You for Joining. You will be notified with the details after successful launch of your instance. "
    else
      params_id = params[:id]
    end
    @product = current_user.products.find(params_id)
    @subscriptions = @product.subscriptions if @product
    respond_with @product, @subscriptions
  end

  def new
    if params[:custom_image_id]
        @image = CustomImage.find_by_id!(params[:custom_image_id])
    end
    respond_with @image, @product = current_user.products.new
  end

  def create
    Product.transaction do
      @product = current_user.products.new(product_params)
      @product.set_attributes
      @product.save!

      paypal_url = @product.paypal_url
      if paypal_url
        redirect_to paypal_url
      else
        redirect_to :back
      end
    end
  end

  def destroy
    product = Product.find(params[:id])
    if product.profileId && product.product_id

      if product.web_name == "AWS"
        response = product.send(:destroy_instance)
        if response[:instances_set].first[:current_state][:name] == "shutting-down"
          ppr = PayPal::Recurring.new(:profile_id => product.profileId)
          ppr.cancel
          product.update_attributes(status: 'terminated')
          subscription = Subscription.find_by_product_id(params[:id])
          subscription.update_attributes(status: "expired")
        end
      elsif product.web_name == "DigitalOcean"
        response = product.send(:destroy_droplet)
        if response.status == "OK"
          ppr = PayPal::Recurring.new(:profile_id => product.profileId)
          ppr.cancel
          product.update_attributes(status: 'terminated')
          subscription = Subscription.where(product_id: product.id, status: "active")
          subscription.first.update_attributes(status: "expired") unless subscription.empty?
        end
      end

    end
    redirect_to :back
  end

  def transaction_details
    product = Product.find(params[:custom])
    Product.transaction do
      if params[:txn_type] == "subscr_signup"
        UserMailer.notification_email(product.user, product).deliver
        product.update_attributes(profileId: params[:subscr_id])
      elsif params[:txn_type] == "subscr_payment" && params[:payment_status] == 'Completed'
        subscript = product.user.subscriptions.where(sub_tran: params[:txn_id])
        unless !subscript.empty?
          unless product.product_id
            if product.web_name == "AWS"
              product_type = product[:product_type]
              size_type = nil
              product.send(:launch_ec2_instance)
            elsif product.web_name == "DigitalOcean"
              size_type = product[:size_type]
              product_type = nil
              product.send(:launch_droplet)
            end
            end_date = product.launch_time + 30.days
            notify_date = end_date - 7.days

            #create subscription
            product.user.subscriptions.create(
             web_type: product.web_name, image_id: product.image_id,
             product_type: product_type, instance_id: product.product_id, sub_tran: params[:txn_id],
             size_type: size_type, user_id: product.user.id, product_id: product.id,
             start_date: product.launch_time, end_date: end_date, notify_date: notify_date, status: 'active'
            )
            product.update_attributes(status: 'launched')
            UserMailer.transaction_email(product.user, product).deliver
          else
            end_date = Date.today + 30.days
            notify_date = end_date - 7.days

            #Expire old subscription 
            prev_sub = Subscription.where(product_id: product.id, status: "active")
            prev_sub.first.update_attributes(status: 'expired') unless prev_sub.empty?

            #create new subscription
            product.user.subscriptions.create(
              web_type: product.web_name, image_id: product.image_id, product_type: product_type,
              instance_id: product.product_id, sub_tran: params[:txn_id], size_type: size_type,
              user_id: product.user.id, product_id: product.id, start_date: product.launch_time,
              end_date: end_date, notify_date: notify_date, status: 'active'
            )
            product.update_attributes(status: 'launched')
            UserMailer.new_payment_email(product.user, product).deliver
          end
        end
      elsif params[:txn_type] == "subscr_cancel"
        UserMailer.delete_instance(product.user, product).deliver
      end
    end
    redirect_to servers_path
  end
  
  def set_digital_ocean
    if AppConfig.cloud[:name] == "DigitalOcean"
      Digitalocean.client_id  = AppConfig.cloud[:creds][:access_key]
      Digitalocean.api_key    = AppConfig.cloud[:creds][:secret_token]
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :product_type, :size_type,
          :image_id, :region, :custom_image_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(product)
    image_path = case product
    when "vT6Basic"
      "Vtiger-logo.png"
    when "Sugar6516"
      "logo_sugarcrm.png"
    when "RailsImage"
      "rails.png"
    end
    image_tag image_path, class: 'img-responsive', style: 'text-align:center'
  end
end

app/views/products/index.html.erb
<% content_for :page_styles do %>
	<%= stylesheet_link_tag "select2_metro", media: "all" %>
	<%= stylesheet_link_tag "DT_bootstrap", media: "all" %>
<% end %>

<% content_for :header do %>
	My Servers
<% end %>

<% content_for :breadcrumbs do %>
	<li class="btn-group">
		<a class="btn blue" href="<%= launch_server_path %>" style="color:white;"><i class="fa fa-rocket"></i> Launch Server</a>
	</li>
	<li>
		<i class="fa fa-home"></i>
		<a href="/">
		Home </a>
	</li>
<% end %>
<table class="table table-striped table-bordered table-hover" id="sample_1">
	<thead>
		<tr>
			<th>Name</th>
			<th class='hidden-480'>Server ID</th>
			<%if AppConfig.cloud[:name] == "AWS"%>
			<th class='hidden-phone'>Server Type</th>
			<%elsif AppConfig.cloud[:name] == "DigitalOcean"%>
			<th class='hidden-phone'>Size Type</th>
			<%end%>
			<th>Launch Time</th>
			<th class='hidden-480'>Cost</th>
			<th class='hidden-480'>Status</th>
			<th class="center">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |instance| %>
		<tr>
			<td><%= instance.name %></td>
			<td><%= instance.product_id %></td>
			<%if AppConfig.cloud[:name] == "AWS"%>
			<td><%= instance.product_type %></td>
			<%else%>
			<td><%= SizeType.find_by_size_id(instance.size_type).name %></td>
			<%end%>
			<td><%= instance.launch_time %></td>
			<td><%= instance.cost%></td>
			<% inst_state = instance.status || "unknown" %>
			<td>
			<%= content_tag :span, class: instance_state_class(inst_state) do %>
				<%= inst_state.camelize %>
			<% end %>
			</td>
			<td>
				<a href="<%= server_path(instance) %>" class="btn blue btn-xs" data-rel="tooltip" title="View Details"><i class="fa fa-list"></i></a>
				<% if inst_state and inst_state == 'launched' and instance.product_id %>
					<%= link_to "/servers/#{instance.id}", method: :delete, confirm: "Are you sure?", class: "btn red btn-xs", title: "Terminate Server" do %>
						<i class="fa fa-trash-o"></i>
					<% end %>
				<% end %>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>

<% content_for :page_scripts do %>
	<%= javascript_include_tag "jquery.dataTables.min" %>
	<%= javascript_include_tag "DT_bootstrap" %>
	<%= javascript_include_tag "select2.min" %>
<% end %>

<% content_for :inline_scripts do %>
<script type="text/javascript">
	window.onload = function() {
		$('li#nav-elements-server').addClass('active');
		var oTable = $('#sample_1').dataTable({
			"aoColumnDefs" : [{
				"bSortable" : false,
				"aTargets" : [6]
			}],
			"aaSorting" : [[1, 'asc']],
			"aLengthMenu" : [[5, 15, 20, -1], [5, 15, 20, "All"] // change per page values here
			],
			// set the initial value
			"iDisplayLength" : 10,
		});
		jQuery('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small"); // modify table search input
		jQuery('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
		jQuery('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
	}; 
</script>
<% end %>

app/views/products/new.html.erb
<% content_for :header do %>
	Launch Server
<% end %>

<% content_for :breadcrumbs do %>
	<li>
		<i class="fa fa-home"></i>
		<a href="/">
		Home </a>
		<i class="fa fa-angle-right"></i>
	</li>
	<li>
		Launch Server
	</li>
<% end %>

<div class="portlet box red">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Fill Details For New Server
		</div>
	</div>
	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<%= form_for @product, url: servers_path, html: {id: 'validation-form', class: 'form-horizontal'} do |f| %>
			<div class="form-body">
				<div class="form-group">
					<label class="col-md-3 control-label">Name Your Server :</label>
					<div class="col-md-4">
						<%= f.text_field :name, class: "form-control", id: "name", required: true, maxlength:"128", placeholder: "Enter Name" %>
						<span class="help-block"> (a-z, A-Z, 0-9) </span>
					</div>
				</div>
				<% if params[:custom_image_id] %>
					<%= f.hidden_field :custom_image_id, {:value => params[:custom_image_id]} %>
				<% end %>
				<% if !params[:custom_image_id] %>
				<div class="form-group">
					<label class="col-md-3 control-label">Select Image:</label>
					<div class="col-md-9">
						<% if AppConfig.cloud[:name] == "AWS" %>
							<%= f.select :image_id, AppConfig.ami_ids,{}, {class: "form-control", id: "ami"} %>
						<% elsif %>
							<% AppConfig.image_ids.each do |id| %>
								<div class="col-md-3 well images" style="cursor:pointer;">
									<input type="radio" name="product[image_id]" class="product_image hidden" value="<%= id.last %>" />
									<%= product_image id.first %>
								</div>
								<div class="col-md-1"></div>
							<% end %>
						<% end %>
					</div>
				</div>
			<% if AppConfig.cloud[:name] == "AWS" %>
				<% ProductType.all.each do |it| %>
					<div class="form-group">
						<div class="col-md-3 control-label">
							<input type="radio" name="product[size_type]" class="product_type" value="<%= it.size_id %>" />&nbsp;<label><b><%= it.name %></b></label>
						</div>
						<div class="col-md-3 form-container">
							<div class="row"><%= it.memory %></div>
							<div class="row"><%= it.cost %></div>
						</div>
					</div>
				<% end %>
			<% elsif AppConfig.cloud[:name] == "DigitalOcean" %>
				<div class="form-group">
					<label class="col-md-3 control-label">Select Size :</label>
					<div class="col-md-9">
						<% SizeType.all.each do |it| %>
							<div class="col-md-3 well sizes" style="cursor:pointer;" id="<%= it.name.downcase %>">
								<input type="radio" name="product[size_type]" class="product_type hidden" value="<%= it.size_id %>" />
								<h4 class="text-center"><b><%= it.name %></b></h4>
								<div class="row text-center"><%= it.memory %> Memory</div>
								<div class="row text-center"><%= it.disk %> GB SSD Disk</div>
								<div class="row text-center"><%= it.cost %></div>
							</div>
							<div class="col-md-1"></div>
						<% end %>
					</div>
				</div>
				<% end %>
			<% end %>
		</div>
		<div class="form-actions fluid">
			<div class="col-md-offset-3 col-md-9">
				<button type="submit" class="btn blue">
					Submit
				</button>
				<%= link_to "Cancel", servers_path, class: "btn default" %>
			</div>
		</div>
		<% end %>
		<!-- END FORM-->
	</div>
</div>

<% content_for :inline_scripts do %>
	<script type="text/javascript">
		window.onload = function() {
			$('li#nav-elements-launch').addClass('active');
			select_radio_option = function($option, $choices) {
				$choices.removeAttr('checked');
				$option.prop('checked', true);
			};
			highlight_div = function($div, $elements) {
				$elements.removeClass('highlight');
				$div.addClass('highlight');
			};
			$(document).on('click', 'div.images', function(){
				highlight_div($(this), $('div.images'));
				$radio = $(this).find('input.product_image');
				select_radio_option($radio, $('input.product_image'))
			});
			$(document).on('click', 'div.sizes', function(){
				highlight_div($(this), $('div.sizes'));
				$radio = $(this).find('input.product_type');
				select_radio_option($radio, $('input.product_type'))
			});
			$("#name").keypress(function(event){
				if (event.altKey == false && event.ctrlKey == false)
					if (!((event.keyCode >= 48 && event.keyCode <= 57 && event.shiftKey== false) ||
						(event.keyCode >= 65 && event.keyCode <= 90) ||
						(event.keyCode >= 97 && event.keyCode <= 122) || event.keyCode == 8 || event.keyCode == 46))
						event.preventDefault();
			});
			<% if params[:type] && %w(basic small business).include?(params[:type]) %>
				$("div#" + "<%= params[:type] %>").trigger('click');
			<% else %>
				$('div.sizes:first').trigger('click');
			<% end %>
			$('div.images:first').trigger('click');
			
		};
	</script>
<% end %>

app/views/products/show.html.erb
<% content_for :page_styles do %>
	<%= stylesheet_link_tag "select2_metro", media: "all" %>
	<%= stylesheet_link_tag "DT_bootstrap", media: "all" %>
<% end %>

<% content_for :header do %>
	Server Details
<% end %>

<% content_for :breadcrumbs do %>
	<li class="btn-group">
		<% if @product.status == "launched" and @product.product_id %>
			<%= link_to server_path(@product),  method: :delete, action: :destroy, confirm: "Are you sure ?", class: "btn red", style: "color:#fff;" do%>
				<i class="fa fa-trash-o"></i>Terminate
			<% end %>
		<% end %>
	</li>
	<li>
		<i class="fa fa-home"></i>
		<a href="/">
		Home </a>
		<i class="fa fa-angle-right"></i>
	</li>
	<li>
		<%= @product.name.try(:humanize) %>
	</li>
<% end %>
<div class="portlet box red">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Basic Details
		</div>
		<div class="tools">
			<%= link_to "", server_path(@product), class: "reload" %>
		</div>
	</div>
	<div class="portlet-body form">
		<!-- BEGIN FORM-->
		<form class="form-horizontal" role="form">
			<div class="form-body">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Name:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= @product.name.try(:humanize)%>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Server ID:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= @product.product_id ? @product.product_id : '-' %>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Launch Time:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= @product.launch_time ? @product.launch_time : '-' %>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Cost:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									$ <%= @product.cost %> per Month
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">
								<%= AppConfig.cloud[:name] == "DigitalOcean" ? 'Size Type:' : 'Server Type:' %>
							</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%if AppConfig.cloud[:name] == "AWS"%>
										<%= @product.product_type %>
									<% elsif AppConfig.cloud[:name] == "DigitalOcean" %>
										<%= SizeType.find_by_size_id(@product.size_type).name %>
									<%end%>
								</p>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Image ID:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= @product.image_id %>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">Status:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= content_tag :span, class: instance_state_class(@product.status) do %>
										<%= @product.status.camelize if @product.status %>
									<% end %>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label col-md-3">DNS Name:</label>
							<div class="col-md-9">
								<p class="form-control-static">
									<%= @product.dns_name %>
								</p>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
			</div>
		</form>
		<!-- END FORM-->
	</div>
</div>
<div class="portlet box green">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Subscriptions
		</div>
	</div>
	<div class="portlet-body">
		<table class="table table-striped table-bordered table-hover" id="subscribe_table">
			<thead>
				<tr>
					<th >Server ID</th>
					<th>Web Type</th>
					<th>Product Type</th>
					<th>Image ID</th>
					<th>Subscribed On</th>
					<th>Renewal Date</th>
					<th >Status</th>
				</tr>
			</thead>
			<tbody>
				<% if @subscriptions %>
					<% @subscriptions.each do |subscription|%>
						<tr>
							<td><%= subscription.product ? subscription.product.product_id : '-' %></td>
							<td><%= subscription.web_type %></td>
							<td><%= subscription.product_type %></td>
							<td><%= subscription.image_id %></td>
							<td><%= subscription.start_date %></td>
							<td><%= subscription.end_date %></td>
							<td>
								<%= content_tag :span, class: subscription_state_class(subscription.status) do %>
									<%= subscription.status.camelize if subscription.status %>
								<% end %>
							</td>
						</tr>
					<%end%>
				<%end%>
			</tbody>
		</table>
	</div>
</div>

<% content_for :page_scripts do %>
	<%= javascript_include_tag "jquery.dataTables.min" %>
	<%= javascript_include_tag "DT_bootstrap" %>
	<%= javascript_include_tag "select2.min" %>
<% end %>

<% content_for :inline_scripts do %>
	<script type="text/javascript">
		window.onload = function() {
			$('li#nav-elements-server').addClass('active');
			var oTable = $('#subscribe_table').dataTable({
				"aoColumnDefs" : [{
					"bSortable" : false,
					"aTargets" : [6]
				}],
				"aaSorting" : [[0, 'asc']],
				"aLengthMenu" : [[5, 15, 20, -1], [5, 15, 20, "All"] // change per page values here
				],
				// set the initial value
				"iDisplayLength" : 10,
			});
			jQuery('#subscribe_table_wrapper .dataTables_filter input').addClass("form-control input-small");// modify table search input
			jQuery('#subscribe_table_wrapper .dataTables_length select').addClass("form-control input-small");// modify table per page dropdown
			jQuery('#subscribe_table_wrapper .dataTables_length select').select2();
		};

</script>
<% end %>