config/routes.rb
LoginApp::Application.routes.draw do

  resources :subscriptions

  get "authentication/index"
  get "authentication/create"
  get "authentication/destroy"
  resources :servers, controller: "products"
  namespace :admin do
    resources :custom_images
  end

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: 'users/confirmations' }
  devise_scope :user do
    match 'login', to: "users/sessions#new", via: [:get, :post], as: "login"
    get "logout", to: "devise/sessions#destroy", as: "logout"
    match '/add_mail' => 'users/registrations#add_mail', via: [:get, :post]
    get '/auth/failure' => "users/sessions#new"
    get 'return' => "users/sessions#new"
  end
  root 'welcome#landing'
  match '/auth/:provider/callback' => 'authentication#create', via: [:get, :post]
  get "/launch_server" => "products#new", as: :launch_server
  get "/transaction_completed" => "products#show"
  match "/transaction_payment" => "products#transaction_details", via: [:get, :post]
  get '/pricing' => "welcome#pricing"
  get '/faq' => "static_pages#tos"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#error"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  def provider_name
    provider.titleize
  end
end

app/models/custom_image.rb
class CustomImage < ActiveRecord::Base
end

app/models/instance_type.rb
include ActionView::Helpers::NumberHelper

class InstanceType < ActiveRecord::Base

  def memory
    unless self[:memory].blank?
      self[:memory].to_s + " GiB"
    else
      "0 GiB"
     end
  end

  def cost_type
    unless self[:cost].blank?
      "$" + number_with_precision(self[:cost], precision: 2).to_s + " per Month"
    else
      "$ 0 per Month"
    end
  end
end

app/models/product.rb
include ActionView::Helpers::NumberHelper

class Product < ActiveRecord::Base
  include AwsAction

  belongs_to :user

  has_many :subscriptions
  default_scope { order('status') }

  before_create :add_ssh_keys

  def paypal_url
    if custom_image_id
      val = "Custom Image #{custom_image_id}"
    else
      if web_name == "AWS"
        val = product_type
      elsif web_name == "DigitalOcean"
        val = SizeType.find_by_size_id(size_type).name
      end
    end
    values = {
      :business => AppConfig.business_email,
      :cmd => '_xclick-subscriptions',
      :upload => 1,
      :item_name => name + ' (' + val + ')',
      :a3 => number_with_precision(cost, precision: 0),
      :p3 => '1',
      :t3 => 'M',
      :no_note => '1',
      :src => '1',
      :sra => '1',
      :cancel_return => AppConfig.cancel_url,
      :custom => id
    }
    AppConfig.paypal_url + "cgi-bin/webscr?" + values.to_query
  end
  
  def add_ssh_keys
    key = SSHKey.generate
    self[:private_ssh_key] = key.private_key
    self[:public_ssh_key] = key.ssh_public_key
  end

  # set_attributes
  # To be called only when cost and other calculable attributes are to be set.
  def set_attributes
    self.web_name = AppConfig.cloud[:name]
    if self.custom_image_id
      ci = CustomImage.find_by_id!(custom_image_id)
      self.cost = ci.price
      self.region = ci.region
      self.image_id = ci.remote_image_id

      #Map product_type or size_type since that is being used across the app.
      if ci.hosting == "AWS"
        pt = ProductType.find_by_memory!(ci.ram)
        self.product_type = pt.name
        self.size_type = nil
      elsif ci.hosting == "DigitalOcean"
        st = SizeType.find_by_memory!(ci.ram)
        self.size_type = st.size_id
        self.product_type = nil
      end
    else
      if type == "AWS"
        self.cost = ProductType.find_by_name(params[:product][:product_type]).cost_per_month
      elsif type == "DigitalOcean"
        self.cost = SizeType.find_by_size_id(params[:product][:size_type]).cost_per_month
      end
    end

    self.status = 'pending'
  end
end

app/models/product_type.rb
include ActionView::Helpers::NumberHelper

class ProductType < ActiveRecord::Base
  
  def memory
    unless self[:memory].blank?
      self[:memory].to_s + " GiB"
    else
      "0 GiB"
     end
  end

  def cost
    unless self[:cost_per_month].blank?
      "$" + number_with_precision(self[:cost_per_month], precision: 2).to_s + " per Month"
    else
      "$ 0 per Month"
    end
  end
end

app/models/region_type.rb
class RegionType < ActiveRecord::Base
end

app/models/size_type.rb
include ActionView::Helpers::NumberHelper

class SizeType < ActiveRecord::Base

  def memory
    unless self[:memory].blank?
      if self[:memory].to_s == "512.0"
        self[:memory].to_s + " MB"
      else
        self[:memory].to_s + " GiB"
      end
    else
      "0 GiB"
     end
  end

  def cost
    unless self[:cost_per_month].blank?
      "$" + number_with_precision(self[:cost_per_month], precision: 2).to_s + " per Month"
    else
      "$ 0 per Month"
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :products, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :authentications, :dependent => :delete_all
  def apply_omniauth(auth) 
    self.email = auth['info']['email'] 
    authentications.build(:provider => auth['provider'], :uid => auth['uid'], :token => auth['credentials']['token']) 
  end
  
  include Gravtastic
  gravtastic

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
  end

  def error
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
   case type
     when :alert
       "alert alert-error"
     when :error
       "alert alert-error"
     when :notice
       "alert alert-success"
     else
       ""
     end
  end
 
  def instance_state_class(state)
    case state
     when 'pending'
       "label label-warning"
     when 'launched'
       "label label-success"
     when 'terminated'
       "label label-danger"
     else
       "label"
     end
  end
  
  def subscription_state_class(state)
    case state
     when 'pending'
       "label label-warning"
     when 'active'
       "label label-success"
     when 'expired'
       "label label-danger"
     else
       "label"
     end
  end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/aws_actions_helper.rb
module AwsActionsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(product)
    image_path = case product
    when "vT6Basic"
      "Vtiger-logo.png"
    when "Sugar6516"
      "logo_sugarcrm.png"
    when "RailsImage"
      "rails.png"
    end
    image_tag image_path, class: 'img-responsive', style: 'text-align:center'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
	<!-- BEGIN HEAD -->
	<head>
		<meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
		<meta content="Servers" name="description"/>
		<meta content="enbake" name="author"/>
		<meta name="MobileOptimized" content="320">
		<%= csrf_meta_tags %>

		<title><%= content_for?(:title) ? yield(:title) : "Mops" %></title>

		<!-- BEGIN GLOBAL MANDATORY STYLES -->
		<%= stylesheet_link_tag "font-awesome.min", media: "all" %>
		<%= stylesheet_link_tag "bootstrap.min", media: "all" %>
		<%= stylesheet_link_tag "uniform.default.min", media: "all" %>
		<!-- END GLOBAL MANDATORY STYLES -->
		
		<!-- BEGIN PAGE LEVEL STYLES -->
		<%= stylesheet_link_tag "toastr.min", media: "all" %>
		<%= yield :page_styles %>
		<!-- END PAGE LEVEL SCRIPTS -->

		<!-- BEGIN THEME STYLES -->
		<%= stylesheet_link_tag "style-metronic", media: "all" %>
		<%= stylesheet_link_tag "style", media: "all" %>
		<%= stylesheet_link_tag "style-responsive", media: "all" %>
		<%= stylesheet_link_tag "plugins", media: "all" %>
		<%= stylesheet_link_tag "light", media: "all" %>
		<%= stylesheet_link_tag "custom", media: "all" %>
		<!-- END THEME STYLES -->

		<!-- page specific plugin styles -->

		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
	</head>
	<!-- END HEAD -->

	<!-- BEGIN BODY -->
	<body class="page-header-fixed">

		<!-- BEGIN HEADER -->
		<div class="header navbar navbar-inverse navbar-fixed-top">
			<!-- BEGIN TOP NAVIGATION BAR -->
			<div class="header-inner">
				<!-- BEGIN LOGO -->
				<a class="navbar-brand" href="<%= root_path %>" style="padding-top:3px;">
					<%= image_tag "logo_mops.png", alt: "logo", class: "img-responsive" %>
				</a>
				<!-- END LOGO -->
				<!-- BEGIN RESPONSIVE MENU TOGGLER -->
				<a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<%= image_tag "menu-toggler.png", alt: "" %>
				</a>
				<!-- END RESPONSIVE MENU TOGGLER -->
				<!-- BEGIN TOP NAVIGATION MENU -->
				<ul class="nav navbar-nav pull-right">

					<!-- BEGIN USER LOGIN DROPDOWN -->
					<li class="dropdown user">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<%= image_tag current_user.gravatar_url(:size => 29)%>
						<span class="username">
							<%= current_user.email %>
						</span>
						<i class="fa fa-angle-down"></i>
						</a>
						<ul class="dropdown-menu">
							<!--
							<li>
								<a href="#"><i class="fa fa-user"></i> My Profile</a>
							</li>
							<li class="divider">
							</li>-->
							<li>
								<a href="/logout"><i class="fa fa-key"></i> Log Out</a>
							</li>
						</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->

				</ul>
				<!-- END TOP NAVIGATION MENU -->
			</div>
			<!-- END TOP NAVIGATION BAR -->
		</div>
		<!-- END HEADER -->

		<div class="clearfix">
		</div>

		<!-- BEGIN CONTAINER -->
		<div class="page-container">
			<!-- BEGIN SIDEBAR -->
			<div class="page-sidebar-wrapper">
				<div class="page-sidebar navbar-collapse collapse">
					<!-- BEGIN SIDEBAR MENU -->
					<ul class="page-sidebar-menu">
						<li class="sidebar-toggler-wrapper">
							<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
							<div class="sidebar-toggler hidden-phone">
							</div>
							<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
						</li>
						<li class="sidebar-search-wrapper">
							<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
							<form action="extra_search.html" method="POST">
								<div class="form-container">
									<div class="input-box" style="visibility: hidden;">
										<a href="javascript:;" class="remove"></a>
										<input type="text" placeholder="Search..."/>
										<input type="button" class="submit" value=" "/>
									</div>
								</div>
							</form>
							<!-- END RESPONSIVE QUICK SEARCH FORM -->
						</li>
						<!--<li class="start" id="nav-elements-dashboard">
							<a href="/">
							<i class="fa fa-home"></i>
							<span class="title">
								Dashboard
							</span>
							</a>
						</li>-->
						<li class="start" id="nav-elements-server">
							<a href="<%= servers_path %>">
								<i class="fa fa-tasks"></i>
								<span class="title">
									My Servers
								</span>
							</a>
						</li>
						<li class="last" id="nav-elements-launch">
							<a href="<%= launch_server_path %>">
								<i class="fa fa-rocket"></i>
								<span class="title">
									Launch Server
								</span>
							</a>
						</li>
					</ul>
					<!-- END SIDEBAR MENU -->
				</div>
			</div>
			<!-- END SIDEBAR -->
			<!-- BEGIN CONTENT -->
			<div class="page-content-wrapper">
				<div class="page-content">
					<!-- BEGIN PAGE HEADER-->
					<div class="row">
						<div class="col-md-12">
							<!-- BEGIN PAGE TITLE & BREADCRUMB-->
							<h3 class="page-title">
								<%= yield :header %>
							</h3>
							<ul class="page-breadcrumb breadcrumb">
								<%= yield :breadcrumbs %>
							</ul>
							<!-- END PAGE TITLE & BREADCRUMB-->
						</div>
					</div>
					<!-- END PAGE HEADER-->
					<!-- BEGIN PAGE CONTENT-->
					<div class="row">
						<div class="col-md-12">
							<%= yield %>
						</div>
					</div>
					<!-- END PAGE CONTENT-->
				</div>
			</div>
			<!-- END CONTENT -->
		</div>
		<!-- END CONTAINER -->
	
		<!-- BEGIN FOOTER -->
		<div class="footer">
			<div class="footer-inner">
				
			</div>
			<div class="footer-tools">
				<span class="go-top">
					<i class="fa fa-angle-up"></i>
				</span>
			</div>
		</div>
		<!-- END FOOTER -->

		<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
		<!-- BEGIN CORE PLUGINS -->
		<!--[if lt IE 9]>
			<script src="assets/plugins/respond.min.js"></script>
			<script src="assets/plugins/excanvas.min.js"></script> 
		<![endif]-->
		<%= javascript_include_tag :application %>
		<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
		<!-- END CORE PLUGINS -->
		
		<!-- page specific plugin scripts -->
		<%= yield :page_scripts %>

		<%= javascript_include_tag "app" %>

		<script>
			jQuery(document).ready(function() {
				App.init();
				toastr.options = {"closeButton": true, "debug": false, "positionClass": "toast-top-right",
									"onclick": null, "showDuration": "300", "hideDuration": "1000",
									"timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing",
									"hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut"}
				<% flash.each do |type, message| %>
					<% if type == :notice %>
						toastr.success("<%= message%>");
					<% else %>
						toastr.error("<%= message%>");
					<% end %>
				<% end %>
			});
		</script>
		<script type="text/javascript">
			jQuery(document).ready(function() {
				//Hide the overview when click
				$('#someid').on('click', function () {
					$('#OverviewcollapseButton').removeClass("collapse").addClass("expand"); 
					$('#PaymentOverview').hide();
				});
			});
		</script>
		
		<!-- inline scripts related to this page -->
		<%= yield :inline_scripts %>
		<!-- END JAVASCRIPTS -->
	</body>
<!-- END BODY -->
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
	<!-- BEGIN HEAD -->
	<head>
		<meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
		<meta content="Servers" name="description"/>
		<meta content="enbake" name="author"/>
		<meta name="MobileOptimized" content="320">
		<%= csrf_meta_tags %>

		<!-- BEGIN GLOBAL MANDATORY STYLES -->
		<%= stylesheet_link_tag "font-awesome.min", media: "all" %>
		<%= stylesheet_link_tag "bootstrap.min", media: "all" %>
		<!-- END GLOBAL MANDATORY STYLES -->

		<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
		<%= stylesheet_link_tag "jquery.fancybox", media: "all" %>
		<%= stylesheet_link_tag "rs-style.css", media: "all" %>
		<%= stylesheet_link_tag "settings", media: "all" %>
		<%= stylesheet_link_tag "jquery.bxslider", media: "all" %>
		<!-- END PAGE LEVEL PLUGIN STYLES -->

		<!-- BEGIN THEME STYLES -->
		<%= stylesheet_link_tag "toastr.min", media: "all" %>
		<%= stylesheet_link_tag "style-metronic-fontend", media: "all" %>
		<%= stylesheet_link_tag "style-fontend", media: "all" %>
		<%= stylesheet_link_tag "prices", media: "all" %>
		<%= stylesheet_link_tag "red", media: "all" %>
		<%= stylesheet_link_tag "style-responsive-fontend", media: "all" %>
		<%= stylesheet_link_tag "custom-fontend", media: "all" %>
		<!-- END THEME STYLES -->

		<link rel="shortcut icon" href="assets/favicon.ico" />
	</head>
	<!-- END HEAD -->

	<!-- BEGIN BODY -->
	<body>

		<!-- BEGIN HEADER -->
		<div class="header navbar navbar-default navbar-static-top">
			<!-- BEGIN TOP BAR -->
			<div class="front-topbar">
				<div class="container">
					<div class="row">
						<div class="col-md-9 col-sm-9">
							<ul class="list-unstyle inline">
								<li><i class="fa fa-phone topbar-info-icon top-2"></i>Call us: <span>(+91)-11-4745-4482</span></li>
								<li class="sep"><span>|</span></li>
								<li><i class="fa fa-envelope-o topbar-info-icon top-2"></i>Email: <span>consulting@enbake.com</span></li>
							</ul>
						</div>
						<div class="col-md-3 col-sm-3 login-reg-links">
							<ul class="list-unstyled inline">
								<% if user_signed_in? %>
									<li><%= link_to 'Dashboard', servers_path %></li>
									<li class="sep"><span>|</span></li>
									<li><%= link_to 'Logout', logout_path %></li>
								<% else %>
									<li><%= link_to 'Login', login_path %></li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- END TOP BAR -->

			<div class="container">
				<div class="navbar-header">
					<!-- BEGIN RESPONSIVE MENU TOGGLER -->
					<button class="navbar-toggle btn navbar-btn" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- END RESPONSIVE MENU TOGGLER -->
					<!-- BEGIN LOGO (you can use logo image instead of text)-->
					<a class="navbar-brand logo-v1" href="/">
						<%= image_tag "logo_mops.png", class: "img-responsive", id: "logoimg.png"%>
					</a>
					<!-- END LOGO -->
				</div>

				<!-- BEGIN TOP NAVIGATION MENU -->
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li class="dropdown active">
							<a data-close-others="true" href="/"> Home </a>

						</li>
						<li class="dropdown">
							<a class="dropdown-toggle" data-close-others="true" href="/pricing"> Pricing </a>

						</li>
						<li class="dropdown"><a  href="http://blog.enbake.com/" target="_blank"> Blog </a>
						<li class="dropdown"><a class="dropdown-toggle" data-close-others="true" href="/faq">FAQ</a></li>

						</li>

					</ul>
				</div>
				<!-- BEGIN TOP NAVIGATION MENU -->
			</div>
		</div>
		<!-- END HEADER -->

		<!-- BEGIN PAGE CONTAINER -->
		<div class="page-container">
			<%= yield %>
		</div>
		<!-- END PAGE CONTAINER -->

		<!-- BEGIN FOOTER -->
		<div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-4 space-mobile">
						<!-- BEGIN ABOUT -->
						<h2>About</h2>
						<p class="margin-bottom-30">Enbake is a Technology and Consulting firm Specialising with expertise CRM and ERP Applications. We have been in business for 7+ years and have worked as technology partner with 100+ happy Clients.</p>
						<div class="clearfix"></div>
						<!-- END ABOUT -->
					</div>
					<div class="col-md-4 col-sm-4 col-md-push-1 space-mobile">
						<!-- BEGIN CONTACTS -->
						<h2>Contact Us</h2>
						<address class="margin-bottom-40">
							1853/10
							<br />
							Bhagirath Palace
							<br />
							Delhi 110006
							<br />
							India
							<br />
							P: +91-11-4745-4482
							<br />
							Email: <a href="mailto:consulting@enbake.com">consulting@enbake.com</a>
						</address>
						<!-- END CONTACTS -->
					</div>
					<div class="col-md-4 col-sm-4">
						<!-- BEGIN TWITTER BLOCK -->
						<div id="tweets">
							<a class="twitter-timeline" href="https://twitter.com/enbake" data-widget-id="434027135754186753" data-tweet-limit="1">Tweets by @enbake</a>
						</div>
						<!-- END TWITTER BLOCK -->
					</div>
				</div>
			</div>
		</div>
		<!-- END FOOTER -->

		<!-- BEGIN COPYRIGHT -->
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-sm-8">
						<p>
							<span class="margin-right-10">Copyright © 2014 Enbake Consulting Pvt Ltd. &nbsp; ALL Rights Reserved.</span>
						</p>
					</div>
					<div class="col-md-4 col-sm-4">
						<ul class="social-footer">
							<li>
								<a href="https://www.facebook.com/enbake" target="_blank"><i class="fa fa-facebook"></i></a>
							</li>
							<li>
								<a href="https://plus.google.com/+Enbake" target="_blank"><i class="fa fa-google-plus"></i></a>
							</li>
							<li>
								<a href="https://github.com/enbake" target="_blank"><i class="fa fa-github"></i></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<!-- END COPYRIGHT -->

		<!-- Load javascripts at bottom, this will reduce page load time -->
		<!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->
		<!--[if lt IE 9]>
		<script src="assets/plugins/respond.min.js"></script>
		<![endif]-->
		<%= javascript_include_tag "jquery-1.10.2.min" %>
		<%= javascript_include_tag "jquery-migrate-1.2.1.min" %>
		<%= javascript_include_tag "bootstrap.min" %>
		<%= javascript_include_tag "hover-dropdown" %>
		<%= javascript_include_tag "back-to-top" %>
		<!-- END CORE PLUGINS -->

		<!-- BEGIN PAGE LEVEL JAVASCRIPTS(REQUIRED ONLY FOR CURRENT PAGE) -->
		<%= javascript_include_tag "jquery.fancybox.pack" %>
		<%= javascript_include_tag "jquery.themepunch.plugins.min" %>
		<%= javascript_include_tag "jquery.themepunch.revolution.min" %>
		<%= javascript_include_tag "jquery.bxslider.min" %>
		<%= javascript_include_tag "app-frontend" %>
		<%= javascript_include_tag "index-frontend" %>
		<%= javascript_include_tag "toastr.min" %>
		<script type="text/javascript">
			jQuery(document).ready(function() {
				App.init();
				App.initBxSlider();
				Index.initRevolutionSlider();
				
			});
		</script>
		<script>
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
		<!-- END PAGE LEVEL JAVASCRIPTS -->
		<!-- inline scripts related to this page -->
		<%= yield :inline_scripts %>
		<!-- END JAVASCRIPTS -->
		<script>
			jQuery(document).ready(function() {
				App.init();
				toastr.options = {"closeButton": true, "debug": false, "positionClass": "toast-top-right",
									"onclick": null, "showDuration": "300000", "hideDuration": "1000000000",
									"timeOut": "50000000", "extendedTimeOut": "100000000", "showEasing": "swing",
									"hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut"}
				<% flash.each do |type, message| %>
					<% if type == :notice %>
						toastr.success("<%= message%>");
					<% else %>
						toastr.error("<%= message%>");
					<% end %>
				<% end %>
			});
		</script>
	</body>
	<!-- END BODY -->
</html>